// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // __setup__
global.__objectDepths[1] = 0; // Screen
global.__objectDepths[2] = 0; // Time
global.__objectDepths[3] = 0; // Debug
global.__objectDepths[4] = 0; // Resources
global.__objectDepths[5] = 0; // Settings
global.__objectDepths[6] = 0; // Lighting
global.__objectDepths[7] = 9999; // lightingalphadrop
global.__objectDepths[8] = 0; // Input
global.__objectDepths[9] = 0; // objPlayerMain
global.__objectDepths[10] = 0; // objPlayerDeath
global.__objectDepths[11] = 0; // playerGun
global.__objectDepths[12] = 0; // playerInventory
global.__objectDepths[13] = 0; // playerHud
global.__objectDepths[14] = -6; // playerHudStatus
global.__objectDepths[15] = 0; // playerHudGoggles
global.__objectDepths[16] = 0; // objPlayerImp
global.__objectDepths[17] = 0; // objPlayerPaladin
global.__objectDepths[18] = 0; // objPlayerPrincess
global.__objectDepths[19] = 0; // objPlayerTinkerer
global.__objectDepths[20] = -6; // playerHudInfo
global.__objectDepths[21] = -5; // playerHudSpellbook
global.__objectDepths[22] = 2; // playerHudBgInfo
global.__objectDepths[23] = -1; // playerHudBgInfoHp
global.__objectDepths[24] = 0; // enemyBase
global.__objectDepths[25] = 0; // enemyInventory
global.__objectDepths[26] = 0; // enemyTest
global.__objectDepths[27] = 0; // enemyMonster1
global.__objectDepths[28] = 0; // corpseMonster0
global.__objectDepths[29] = 0; // npcRebel
global.__objectDepths[30] = 0; // npcGuard
global.__objectDepths[31] = 0; // npcWarden
global.__objectDepths[32] = 0; // npcBadBitch
global.__objectDepths[33] = 0; // npcToolChargableLamp
global.__objectDepths[34] = 0; // corpseFlyer
global.__objectDepths[35] = 3; // corpseNpc
global.__objectDepths[36] = 0; // bloxBase
global.__objectDepths[37] = 0; // blox32x
global.__objectDepths[38] = 0; // blox32xtriA
global.__objectDepths[39] = 0; // blox32xtriB
global.__objectDepths[40] = 0; // bloxDestroyable
global.__objectDepths[41] = 0; // bloxD32x96
global.__objectDepths[42] = 0; // bloxD32x96_Goo
global.__objectDepths[43] = 0; // doorBase
global.__objectDepths[44] = 0; // doorOnewayLevel
global.__objectDepths[45] = 0; // moverBase
global.__objectDepths[46] = 0; // platform64x32
global.__objectDepths[47] = 0; // debugBox
global.__objectDepths[48] = 0; // debugLine
global.__objectDepths[49] = 0; // debugLineF
global.__objectDepths[50] = -100; // floaterDmgTicker
global.__objectDepths[51] = -900; // floaterLogo
global.__objectDepths[52] = 1; // floaterArea
global.__objectDepths[53] = -20000; // floaterDead
global.__objectDepths[54] = 3; // floaterRoomSummary
global.__objectDepths[55] = 0; // audioSoundPlayer
global.__objectDepths[56] = 0; // audioMusic
global.__objectDepths[57] = 0; // musicAmbientJail0
global.__objectDepths[58] = 0; // musicAmbientJail1
global.__objectDepths[59] = 0; // musicAmbientPrincess0
global.__objectDepths[60] = 0; // fxDustEmitter
global.__objectDepths[61] = -1; // fxDustSm
global.__objectDepths[62] = -1; // fxDustHover
global.__objectDepths[63] = 0; // fxGooEmitterSm
global.__objectDepths[64] = 0; // fxGlueEmitterSm
global.__objectDepths[65] = -1; // fxGooSm
global.__objectDepths[66] = 0; // fxBurnParticle
global.__objectDepths[67] = 0; // fxBloodRedEmitter
global.__objectDepths[68] = -1000; // fxScreenFadeOut
global.__objectDepths[69] = -1000; // fxScreenFadeIn
global.__objectDepths[70] = 0; // fxScreenshake
global.__objectDepths[71] = 0; // fxControllershake
global.__objectDepths[72] = 0; // fxEmissiveEffect
global.__objectDepths[73] = 0; // fxFire0
global.__objectDepths[74] = 0; // fxSparksG0
global.__objectDepths[75] = 0; // fxDust0
global.__objectDepths[76] = 0; // fxLightningBolt
global.__objectDepths[77] = 0; // liLightBase
global.__objectDepths[78] = 2; // liBulbRed
global.__objectDepths[79] = 2; // liToolLightGlow
global.__objectDepths[80] = 0; // liShineGlow
global.__objectDepths[81] = -10; // liGentleWhite50
global.__objectDepths[82] = -1; // liWindowShine
global.__objectDepths[83] = 2; // liCandles0
global.__objectDepths[84] = 1; // liCandles1
global.__objectDepths[85] = -1; // liDoorShine
global.__objectDepths[86] = -1; // liBigMoverShine
global.__objectDepths[87] = 0; // fxShineGlowKiller
global.__objectDepths[88] = -1; // fxCircleExpand
global.__objectDepths[89] = -1; // fxCircleExpandSlow
global.__objectDepths[90] = 1; // fxFader
global.__objectDepths[91] = 1; // fxPlayerShockFlash
global.__objectDepths[92] = 9998; // fxBgVoidParticle
global.__objectDepths[93] = 10001; // fxBgVoidParticleSq
global.__objectDepths[94] = 10001; // fxBgVoidParticleBig
global.__objectDepths[95] = 0; // fxBgVoidParticleEmitter
global.__objectDepths[96] = -10; // menuDebug
global.__objectDepths[97] = -11; // dgbuttonBase
global.__objectDepths[98] = 0; // dgbuttonZoomToggle
global.__objectDepths[99] = 0; // ctsMenu
global.__objectDepths[100] = 0; // ctsIntro
global.__objectDepths[101] = -905; // menuOptions
global.__objectDepths[102] = 0; // levelManager
global.__objectDepths[103] = 0; // levelGenerator
global.__objectDepths[104] = -2; // splatterBase
global.__objectDepths[105] = 0; // splatterGlue
global.__objectDepths[106] = 0; // splatterGoo
global.__objectDepths[107] = 0; // splatterBlood
global.__objectDepths[108] = -2; // projectileSplat
global.__objectDepths[109] = -2; // projectileGlue
global.__objectDepths[110] = -2; // projectileGoo
global.__objectDepths[111] = 0; // projectilePotion
global.__objectDepths[112] = 0; // projectileArrow
global.__objectDepths[113] = 0; // projectileCutsceneArrow
global.__objectDepths[114] = 1; // projectileFireWall
global.__objectDepths[115] = 0; // projectileSmokeWall
global.__objectDepths[116] = 0; // Game
global.__objectDepths[117] = -7; // ctsUpgradeMenu
global.__objectDepths[118] = 0; // tutorialBase
global.__objectDepths[119] = 0; // tutorialJump
global.__objectDepths[120] = 0; // tutorialUse
global.__objectDepths[121] = 0; // tutorialGun
global.__objectDepths[122] = 0; // tutorialModes
global.__objectDepths[123] = -2; // pickupBase
global.__objectDepths[124] = 0; // pickupCoat
global.__objectDepths[125] = 0; // pickupSword
global.__objectDepths[126] = 0; // pickupGooCanister
global.__objectDepths[127] = 0; // pickupGlueCanister
global.__objectDepths[128] = 0; // pickupGun
global.__objectDepths[129] = 0; // pickupGoggles
global.__objectDepths[130] = 0; // pickupGoo
global.__objectDepths[131] = 0; // pickupGlue
global.__objectDepths[132] = 0; // gameEmber
global.__objectDepths[133] = 0; // gameBlooddrop
global.__objectDepths[134] = 5; // junkDoodad
global.__objectDepths[135] = 5; // junkDoodadAnimate
global.__objectDepths[136] = 5; // junkBrokenToob
global.__objectDepths[137] = 4; // junkGoddess
global.__objectDepths[138] = 0; // junkCandles
global.__objectDepths[139] = 0; // buttonBase
global.__objectDepths[140] = 4; // buttonDoorToggle
global.__objectDepths[141] = 3; // buttonUpgradeStation
global.__objectDepths[142] = 4; // buttonBreaker
global.__objectDepths[143] = 0; // buttonInvisi
global.__objectDepths[144] = 2; // aiPathNode
global.__objectDepths[145] = 0; // aiMaster
global.__objectDepths[146] = 0; // ctsTalker
global.__objectDepths[147] = -9; // ctsGabberBox
global.__objectDepths[148] = 0; // ctsTalkerBox
global.__objectDepths[149] = 0; // ctsChoiceBox
global.__objectDepths[150] = 0; // ctsPopup
global.__objectDepths[151] = 0; // cts_TimeExpand
global.__objectDepths[152] = 0; // ctsLibrarianPopup
global.__objectDepths[153] = 0; // spellBase
global.__objectDepths[154] = 0; // spellTest
global.__objectDepths[155] = 0; // spellWall
global.__objectDepths[156] = 0; // transitionBase
global.__objectDepths[157] = 0; // toolLightCharge
global.__objectDepths[158] = 0; // platformStopPoint
global.__objectDepths[159] = 11; // toolChargeGear
global.__objectDepths[160] = 10003; // doodadClouds0
global.__objectDepths[161] = 10002; // doodadJailBg0
global.__objectDepths[162] = 0; // toolGameSave
global.__objectDepths[163] = -10000; // bgJailhouseInside
global.__objectDepths[164] = -10000; // bgJailhouseInsideDark
global.__objectDepths[165] = -10000; // bgJailhouseOutside
global.__objectDepths[166] = -10; // ctsFadeInLongBlack
global.__objectDepths[167] = -10; // ctsFadeOutLongBlack
global.__objectDepths[168] = -20; // ctsTutorialFreeze
global.__objectDepths[169] = 0; // ctsLogoPopup
global.__objectDepths[170] = 0; // ctsVAPopup
global.__objectDepths[171] = 0; // ctsTitlePopup
global.__objectDepths[172] = 0; // ctsLibrary0
global.__objectDepths[173] = 0; // ctsLibrary1
global.__objectDepths[174] = 0; // ctsLibrary2
global.__objectDepths[175] = -1; // ctsLibraryBookcase
global.__objectDepths[176] = 0; // ctsFloaterTitle
global.__objectDepths[177] = 0; // ctsJail0_PaladinIntro
global.__objectDepths[178] = 0; // ctsJail0_AttackTutorial
global.__objectDepths[179] = 0; // ctsJail0_CameraZoomout
global.__objectDepths[180] = 0; // ctsJail0_PaladinRift
global.__objectDepths[181] = 0; // ctsJail0_Prayer
global.__objectDepths[182] = 0; // ctsJail2_GaurdTalk0
global.__objectDepths[183] = 0; // ctsJail2_GaurdTalk1
global.__objectDepths[184] = 0; // ctsJail2_PrincessIntro
global.__objectDepths[185] = 0; // ctsJail2_GuardTutorial
global.__objectDepths[186] = 0; // pzzPlatformMoveLogic
global.__objectDepths[187] = 0; // ctsKeyPoint


global.__objectNames[0] = "__setup__";
global.__objectNames[1] = "Screen";
global.__objectNames[2] = "Time";
global.__objectNames[3] = "Debug";
global.__objectNames[4] = "Resources";
global.__objectNames[5] = "Settings";
global.__objectNames[6] = "Lighting";
global.__objectNames[7] = "lightingalphadrop";
global.__objectNames[8] = "Input";
global.__objectNames[9] = "objPlayerMain";
global.__objectNames[10] = "objPlayerDeath";
global.__objectNames[11] = "playerGun";
global.__objectNames[12] = "playerInventory";
global.__objectNames[13] = "playerHud";
global.__objectNames[14] = "playerHudStatus";
global.__objectNames[15] = "playerHudGoggles";
global.__objectNames[16] = "objPlayerImp";
global.__objectNames[17] = "objPlayerPaladin";
global.__objectNames[18] = "objPlayerPrincess";
global.__objectNames[19] = "objPlayerTinkerer";
global.__objectNames[20] = "playerHudInfo";
global.__objectNames[21] = "playerHudSpellbook";
global.__objectNames[22] = "playerHudBgInfo";
global.__objectNames[23] = "playerHudBgInfoHp";
global.__objectNames[24] = "enemyBase";
global.__objectNames[25] = "enemyInventory";
global.__objectNames[26] = "enemyTest";
global.__objectNames[27] = "enemyMonster1";
global.__objectNames[28] = "corpseMonster0";
global.__objectNames[29] = "npcRebel";
global.__objectNames[30] = "npcGuard";
global.__objectNames[31] = "npcWarden";
global.__objectNames[32] = "npcBadBitch";
global.__objectNames[33] = "npcToolChargableLamp";
global.__objectNames[34] = "corpseFlyer";
global.__objectNames[35] = "corpseNpc";
global.__objectNames[36] = "bloxBase";
global.__objectNames[37] = "blox32x";
global.__objectNames[38] = "blox32xtriA";
global.__objectNames[39] = "blox32xtriB";
global.__objectNames[40] = "bloxDestroyable";
global.__objectNames[41] = "bloxD32x96";
global.__objectNames[42] = "bloxD32x96_Goo";
global.__objectNames[43] = "doorBase";
global.__objectNames[44] = "doorOnewayLevel";
global.__objectNames[45] = "moverBase";
global.__objectNames[46] = "platform64x32";
global.__objectNames[47] = "debugBox";
global.__objectNames[48] = "debugLine";
global.__objectNames[49] = "debugLineF";
global.__objectNames[50] = "floaterDmgTicker";
global.__objectNames[51] = "floaterLogo";
global.__objectNames[52] = "floaterArea";
global.__objectNames[53] = "floaterDead";
global.__objectNames[54] = "floaterRoomSummary";
global.__objectNames[55] = "audioSoundPlayer";
global.__objectNames[56] = "audioMusic";
global.__objectNames[57] = "musicAmbientJail0";
global.__objectNames[58] = "musicAmbientJail1";
global.__objectNames[59] = "musicAmbientPrincess0";
global.__objectNames[60] = "fxDustEmitter";
global.__objectNames[61] = "fxDustSm";
global.__objectNames[62] = "fxDustHover";
global.__objectNames[63] = "fxGooEmitterSm";
global.__objectNames[64] = "fxGlueEmitterSm";
global.__objectNames[65] = "fxGooSm";
global.__objectNames[66] = "fxBurnParticle";
global.__objectNames[67] = "fxBloodRedEmitter";
global.__objectNames[68] = "fxScreenFadeOut";
global.__objectNames[69] = "fxScreenFadeIn";
global.__objectNames[70] = "fxScreenshake";
global.__objectNames[71] = "fxControllershake";
global.__objectNames[72] = "fxEmissiveEffect";
global.__objectNames[73] = "fxFire0";
global.__objectNames[74] = "fxSparksG0";
global.__objectNames[75] = "fxDust0";
global.__objectNames[76] = "fxLightningBolt";
global.__objectNames[77] = "liLightBase";
global.__objectNames[78] = "liBulbRed";
global.__objectNames[79] = "liToolLightGlow";
global.__objectNames[80] = "liShineGlow";
global.__objectNames[81] = "liGentleWhite50";
global.__objectNames[82] = "liWindowShine";
global.__objectNames[83] = "liCandles0";
global.__objectNames[84] = "liCandles1";
global.__objectNames[85] = "liDoorShine";
global.__objectNames[86] = "liBigMoverShine";
global.__objectNames[87] = "fxShineGlowKiller";
global.__objectNames[88] = "fxCircleExpand";
global.__objectNames[89] = "fxCircleExpandSlow";
global.__objectNames[90] = "fxFader";
global.__objectNames[91] = "fxPlayerShockFlash";
global.__objectNames[92] = "fxBgVoidParticle";
global.__objectNames[93] = "fxBgVoidParticleSq";
global.__objectNames[94] = "fxBgVoidParticleBig";
global.__objectNames[95] = "fxBgVoidParticleEmitter";
global.__objectNames[96] = "menuDebug";
global.__objectNames[97] = "dgbuttonBase";
global.__objectNames[98] = "dgbuttonZoomToggle";
global.__objectNames[99] = "ctsMenu";
global.__objectNames[100] = "ctsIntro";
global.__objectNames[101] = "menuOptions";
global.__objectNames[102] = "levelManager";
global.__objectNames[103] = "levelGenerator";
global.__objectNames[104] = "splatterBase";
global.__objectNames[105] = "splatterGlue";
global.__objectNames[106] = "splatterGoo";
global.__objectNames[107] = "splatterBlood";
global.__objectNames[108] = "projectileSplat";
global.__objectNames[109] = "projectileGlue";
global.__objectNames[110] = "projectileGoo";
global.__objectNames[111] = "projectilePotion";
global.__objectNames[112] = "projectileArrow";
global.__objectNames[113] = "projectileCutsceneArrow";
global.__objectNames[114] = "projectileFireWall";
global.__objectNames[115] = "projectileSmokeWall";
global.__objectNames[116] = "Game";
global.__objectNames[117] = "ctsUpgradeMenu";
global.__objectNames[118] = "tutorialBase";
global.__objectNames[119] = "tutorialJump";
global.__objectNames[120] = "tutorialUse";
global.__objectNames[121] = "tutorialGun";
global.__objectNames[122] = "tutorialModes";
global.__objectNames[123] = "pickupBase";
global.__objectNames[124] = "pickupCoat";
global.__objectNames[125] = "pickupSword";
global.__objectNames[126] = "pickupGooCanister";
global.__objectNames[127] = "pickupGlueCanister";
global.__objectNames[128] = "pickupGun";
global.__objectNames[129] = "pickupGoggles";
global.__objectNames[130] = "pickupGoo";
global.__objectNames[131] = "pickupGlue";
global.__objectNames[132] = "gameEmber";
global.__objectNames[133] = "gameBlooddrop";
global.__objectNames[134] = "junkDoodad";
global.__objectNames[135] = "junkDoodadAnimate";
global.__objectNames[136] = "junkBrokenToob";
global.__objectNames[137] = "junkGoddess";
global.__objectNames[138] = "junkCandles";
global.__objectNames[139] = "buttonBase";
global.__objectNames[140] = "buttonDoorToggle";
global.__objectNames[141] = "buttonUpgradeStation";
global.__objectNames[142] = "buttonBreaker";
global.__objectNames[143] = "buttonInvisi";
global.__objectNames[144] = "aiPathNode";
global.__objectNames[145] = "aiMaster";
global.__objectNames[146] = "ctsTalker";
global.__objectNames[147] = "ctsGabberBox";
global.__objectNames[148] = "ctsTalkerBox";
global.__objectNames[149] = "ctsChoiceBox";
global.__objectNames[150] = "ctsPopup";
global.__objectNames[151] = "cts_TimeExpand";
global.__objectNames[152] = "ctsLibrarianPopup";
global.__objectNames[153] = "spellBase";
global.__objectNames[154] = "spellTest";
global.__objectNames[155] = "spellWall";
global.__objectNames[156] = "transitionBase";
global.__objectNames[157] = "toolLightCharge";
global.__objectNames[158] = "platformStopPoint";
global.__objectNames[159] = "toolChargeGear";
global.__objectNames[160] = "doodadClouds0";
global.__objectNames[161] = "doodadJailBg0";
global.__objectNames[162] = "toolGameSave";
global.__objectNames[163] = "bgJailhouseInside";
global.__objectNames[164] = "bgJailhouseInsideDark";
global.__objectNames[165] = "bgJailhouseOutside";
global.__objectNames[166] = "ctsFadeInLongBlack";
global.__objectNames[167] = "ctsFadeOutLongBlack";
global.__objectNames[168] = "ctsTutorialFreeze";
global.__objectNames[169] = "ctsLogoPopup";
global.__objectNames[170] = "ctsVAPopup";
global.__objectNames[171] = "ctsTitlePopup";
global.__objectNames[172] = "ctsLibrary0";
global.__objectNames[173] = "ctsLibrary1";
global.__objectNames[174] = "ctsLibrary2";
global.__objectNames[175] = "ctsLibraryBookcase";
global.__objectNames[176] = "ctsFloaterTitle";
global.__objectNames[177] = "ctsJail0_PaladinIntro";
global.__objectNames[178] = "ctsJail0_AttackTutorial";
global.__objectNames[179] = "ctsJail0_CameraZoomout";
global.__objectNames[180] = "ctsJail0_PaladinRift";
global.__objectNames[181] = "ctsJail0_Prayer";
global.__objectNames[182] = "ctsJail2_GaurdTalk0";
global.__objectNames[183] = "ctsJail2_GaurdTalk1";
global.__objectNames[184] = "ctsJail2_PrincessIntro";
global.__objectNames[185] = "ctsJail2_GuardTutorial";
global.__objectNames[186] = "pzzPlatformMoveLogic";
global.__objectNames[187] = "ctsKeyPoint";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for